/*** Autogenerated by WIDL 7.0 from include/xaudio2fx.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xaudio2fx_h__
#define __xaudio2fx_h__

/* Forward declarations */

#ifndef __AudioVolumeMeter20_FWD_DEFINED__
#define __AudioVolumeMeter20_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter20 AudioVolumeMeter20;
#else
typedef struct AudioVolumeMeter20 AudioVolumeMeter20;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter20_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter21_FWD_DEFINED__
#define __AudioVolumeMeter21_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter21 AudioVolumeMeter21;
#else
typedef struct AudioVolumeMeter21 AudioVolumeMeter21;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter21_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter22_FWD_DEFINED__
#define __AudioVolumeMeter22_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter22 AudioVolumeMeter22;
#else
typedef struct AudioVolumeMeter22 AudioVolumeMeter22;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter22_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter23_FWD_DEFINED__
#define __AudioVolumeMeter23_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter23 AudioVolumeMeter23;
#else
typedef struct AudioVolumeMeter23 AudioVolumeMeter23;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter23_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter24_FWD_DEFINED__
#define __AudioVolumeMeter24_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter24 AudioVolumeMeter24;
#else
typedef struct AudioVolumeMeter24 AudioVolumeMeter24;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter24_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter25_FWD_DEFINED__
#define __AudioVolumeMeter25_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter25 AudioVolumeMeter25;
#else
typedef struct AudioVolumeMeter25 AudioVolumeMeter25;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter25_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter26_FWD_DEFINED__
#define __AudioVolumeMeter26_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter26 AudioVolumeMeter26;
#else
typedef struct AudioVolumeMeter26 AudioVolumeMeter26;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter26_FWD_DEFINED__ */

#ifndef __AudioVolumeMeter27_FWD_DEFINED__
#define __AudioVolumeMeter27_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioVolumeMeter27 AudioVolumeMeter27;
#else
typedef struct AudioVolumeMeter27 AudioVolumeMeter27;
#endif /* defined __cplusplus */
#endif /* defined __AudioVolumeMeter27_FWD_DEFINED__ */

#ifndef __AudioReverb20_FWD_DEFINED__
#define __AudioReverb20_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb20 AudioReverb20;
#else
typedef struct AudioReverb20 AudioReverb20;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb20_FWD_DEFINED__ */

#ifndef __AudioReverb21_FWD_DEFINED__
#define __AudioReverb21_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb21 AudioReverb21;
#else
typedef struct AudioReverb21 AudioReverb21;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb21_FWD_DEFINED__ */

#ifndef __AudioReverb22_FWD_DEFINED__
#define __AudioReverb22_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb22 AudioReverb22;
#else
typedef struct AudioReverb22 AudioReverb22;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb22_FWD_DEFINED__ */

#ifndef __AudioReverb23_FWD_DEFINED__
#define __AudioReverb23_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb23 AudioReverb23;
#else
typedef struct AudioReverb23 AudioReverb23;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb23_FWD_DEFINED__ */

#ifndef __AudioReverb24_FWD_DEFINED__
#define __AudioReverb24_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb24 AudioReverb24;
#else
typedef struct AudioReverb24 AudioReverb24;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb24_FWD_DEFINED__ */

#ifndef __AudioReverb25_FWD_DEFINED__
#define __AudioReverb25_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb25 AudioReverb25;
#else
typedef struct AudioReverb25 AudioReverb25;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb25_FWD_DEFINED__ */

#ifndef __AudioReverb26_FWD_DEFINED__
#define __AudioReverb26_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb26 AudioReverb26;
#else
typedef struct AudioReverb26 AudioReverb26;
#endif /* defined __cplusplus */
#endif /* defined __AudioReverb26_FWD_DEFINED__ */

#ifndef __AudioReverb27_FWD_DEFINED__
#define __AudioReverb27_FWD_DEFINED__
#ifdef __cplusplus
typedef class AudioReverb27 AudioRever